theme = "catppuccin_custom"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
cursorline = true
true-color = true
scrolloff = 8
rulers = [80]

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab =  "goto_next_buffer" 
S-tab =  "goto_previous_buffer" 
"}" = "goto_next_paragraph" 
"{" = "goto_prev_paragraph"   
G = "goto_last_line"   


[keys.normal.space]
x =  ":bc"  
  
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = ""
