# Syntax highlighting
# -------------------
"type" = "yellow"

"constructor" = "sapphire"

"constant" = "peach"
"constant.builtin" = "peach"
"constant.character" = "teal"
"constant.character.escape" = "pink"

"string" = "green"
"string.regexp" = "peach"
"string.special" = "blue"

"comment" = { fg = "overlay1", modifiers = ["italic"] }

"variable" = "text"
"variable.parameter" = { fg = "red", modifiers = ["italic"] }
"variable.builtin" = "red"
"variable.other.member" = "teal"

"label" = "rosewater" # used for lifetimes

"punctuation" = "overlay2"
"punctuation.special" = "sky"

"keyword" = { fg = "mauve", modifiers = ["italic"] }
"keyword.storage.modifier.ref" = "teal"
"keyword.control.conditional" = { fg = "mauve", modifiers = ["italic"] }

"operator" = "sky"

"function" = "blue"
"function.macro" = "mauve"
"function.builtin" = "peach"
"function.method" = "blue"
"function.special" = "maroon"

"tag" = "mauve"
"attribute" = "blue"

"namespace" = { fg = "pink", modifiers = ["italic"] }

"special" = "blue" # fuzzy highlight

"markup.heading.marker" = { fg = "peach", modifiers = ["bold"] }
"markup.heading.1" = "lavender"
"markup.heading.2" = "mauve"
"markup.heading.3" = "green"
"markup.heading.4" = "yellow"
"markup.heading.5" = "pink"
"markup.heading.6" = "teal"
"markup.list" = "mauve"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "rosewater", modifiers = ["underlined"] }
"markup.link.text" = "blue"
"markup.raw" = "flamingo"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"

# User Interface
# --------------
"ui.background" = { fg = "text", bg = "mantle" }

"ui.linenr" = { fg = "surface1", bg = "dark" }
"ui.linenr.selected" = { fg = "lavender" }
"ui.gutter" = { bg = "dark" }

"ui.statusline" = { fg = "subtext1", bg = "base" }
"ui.statusline.inactive" = { fg = "surface2", bg = "mantle" }
"ui.statusline.normal" = { fg = "base", bg = "lavender", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "base", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "base", bg = "flamingo", modifiers = ["bold"] }
"ui.statusline.separator" = { fg = "subtext1"}

"ui.popup" = { fg = "text", bg = "surface0" }
"ui.window" = { fg = "crust" }
"ui.help" = { fg = "overlay2", bg = "surface0" }

"ui.bufferline" = { fg = "subtext0", bg = "mantle" }
# "ui.bufferline.active" = { fg = "base", bg = "green", underline = { color = "mauve", style = "line" } }
"ui.bufferline.active" = { fg = "base", bg = "green" }
"ui.bufferline.background" = { bg = "crust" }

"ui.text" = "text"
"ui.text.focus" = { fg = "text", bg = "surface0" }

"ui.virtual" = "overlay0"
"ui.virtual.ruler" = { bg = "crust"}
"ui.virtual.indent-guide" = "overlay0"
"ui.virtual.inlay-hint" = { fg = "surface1", bg = "base" }

"ui.selection" = { bg = "surface1" }

"ui.cursor" = { fg = "dark", bg = "secondary_cursor" , modifiers = ["slow_blink"] }
"ui.cursor.normal" = { fg = "dark", bg = "secondary_cursor" , modifiers = ["slow_blink"] }
"ui.cursor.primary" = { fg = "dark", bg = "subtext0", modifiers = ["slow_blink"] }
"ui.cursor.primary.select" = { fg = "crust", bg = "subtext0" , underline = {color = "peach", style = "line"} , modifiers = ["bold"]}
"ui.cursor.select" = { fg = "base", bg = "flamingo", underline = {color = "peach", style = "line"}}
"ui.cursor.match" = { fg = "peach", modifiers = ["bold"] }

"ui.cursorline.primary" = { bg = "cursorline" }

"ui.highlight" = { bg = "surface1", modifiers = ["bold"] }

"ui.menu" = { fg = "overlay2", bg = "surface0" }
"ui.menu.selected" = { fg = "text", bg = "surface1", modifiers = ["bold"] }

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "sky", style = "curl" } }
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }

error = "red"
warning = "yellow"
info = "sky"
hint = "teal"

[palette]
# catppuccin palette colors
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
dark = "#11111b2"

text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"

base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# derived colors by blending existing palette colors
cursorline = "#2a2b3c"
secondary_cursor = "#b5a6a8"
